service: GitKrakenGloToDos

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: prod
  profile: Madushan
  versionFunctions: false

  environment:
    # Glo webhook 
    GLO_WEBHOOK_SECRET: ${file(./commons/auths/secrets.env.yml):gloAPI.GLO_WEBHOOK_SECRET}

functions:
  getcardUpdateInfo:
    handler: endpoints/getcardUpdateInfo.handler
    description: Getting card update event sent by Glo api
    events:
      - http:
          method: POST
          path: getCardUpdates