service: GitKrakenGloToDos

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: prod
  profile: Madushan
  versionFunctions: false

  environment:
    # Glo webhook 
    GLO_WEBHOOK_SECRET: ${file(./commons/secrets.env.yml):gloAPI.GLO_WEBHOOK_SECRET}
    # GLO Board info
    BOARD_ID: ${file(./commons/secrets.env.yml):gloBoard.BOARD_ID}
    COLUMN_ID: ${file(./commons/secrets.env.yml):gloBoard.COLUMN_ID}
    # Endpoints
    POST_CARDUPDATES_ENDPOINT: ${file(./commons/secrets.env.yml):endpoints.POST_CARDUPDATES_ENDPOINT}

functions:
  getcardUpdateInfo:
    handler: endpoints/getcardUpdateInfo.handler
    description: Getting card update event sent by Glo api
    events:
      - http:
          method: POST
          path: getCardUpdates
      
    layers:
      - arn:aws:lambda:us-east-2:113088814899:layer:Klayers-python37-requests:12
      - arn:aws:lambda:us-east-2:113088814899:layer:Klayers-python37-pytz:5
  
  postcardUpdateInfo:
    handler: endpoints/postcardUpdateInfo.handler
    description: Posting card updates back to Glo api
    events:
      - http:
          method: POST
          path: postcardUpdateInfo

    layers:
      - arn:aws:lambda:us-east-2:113088814899:layer:Klayers-python37-requests:12
      - arn:aws:lambda:us-east-2:113088814899:layer:Klayers-python37-pytz:5